import type { Metadata } from "next";
import React from "react";
import ClientDrawerLayout from "./ClientDrawerLayout";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <ClientDrawerLayout>
            {children}
          </ClientDrawerLayout>
        </ThemeRegistry>
      </body>
    </html>
  );
}
